### ISSUE TITLE
git configが意図せず書き換えられてしまう

### ISSUE THREAD

**Issue by wataash** [haskell-jp/makeMistakesToLearnHaskell#105]
mmlhを読んだ後、他の関係ないgit作業レポジトリでgit commitすると

```
Author: Haskell-jp Bot <whosekiteneverfly+haskelljp@gmail.com>
```

になっていました。`env GITHUB_ACCESS_TOKEN= PORT= mmlh-reporter --help` を実行したことが原因で、これにより `git config --global` が実行されたものと理解しましたが、これは予想外の挙動でした。

`git config` 実行前にプロンプトを出すようにして、`--override-git-config` をつけるとプロンプト無しで実行される、などとするのが良いと思います。

**Comment by igrep** [comment]
Oh, すみません。Docker image上で実行することしか想定していなかったもので...

**Comment by igrep** [comment]
要は`git config --global`を使わなければいいという話なので、mmlh-reporterにオプションを増やさずとも、 https://github.com/haskell-jp/makeMistakesToLearnHaskell/commit/46d63e0f6401b8b76f38edbb98899f216964f04c という解決策でいかがでしょうか？

まだテストできてないのでデプロイはしてませんが...

**Comment by wataash** [comment]
ありがとうございます、良さそうです！

**Comment by wataash** [comment]
`~/.gitconfig` が書き換わらないことと、cloneした `makeMistakesToLearnHaskell-support/.git/config` に

```
[user]
        email = whosekiteneverfly+haskelljp@gmail.com
        name = Haskell-jp Bot
```

が入っていることが確認できましたー。ご都合良いタイミングでクローズして下さい。
