### ISSUE TITLE
32-bit 版 Windows などの stack バイナリーリリースはもうありません

### ISSUE THREAD

**Issue by kakkun61** [haskell-jp/makeMistakesToLearnHaskell#110]
32-bit Windows MMLH ユーザーを切るか別のインストール方法を README に書くかする必要があります。

> We have reduced the number of platforms that we support with binary releases. The reason behind this is that we've been slowed down in our release process until now with issues trying to build binaries for less common platforms. In order to make sure we can address issues more quickly (like supporting new GHC versions), we're limiting support from the Stack team to:
>
> - Linux 64-bit (static)
> - macOS
> - Windows 64-bit
>
>https://docs.haskellstack.org/en/stable/ChangeLog/#v231

**Comment by igrep** [comment]
正直まだ正式リリースからも遙かに遠いような状態だし、配布形態も今後変える可能性が大いにあるので微妙な気持ちですが一応対応しました。

**Comment by kakkun61** [comment]
リリース前というステータスだったのですね。

**Comment by igrep** [comment]
えぇ、はっきりさせてなくて申し訳ない。ex6ブランチでは依然としてほぼ毎週変更が加えられているので...
