### ISSUE TITLE
WSLではmmlh showが働かない

### ISSUE THREAD

**Issue by cojhal** [haskell-jp/makeMistakesToLearnHaskell#115]
WSL2上のUbuntuを使っていますが、`mmlh show 1`を実行すると以下のようなエラーメッセージが標準出力に出されます。

> /tmp/mmlh-ex1.html: 1: xdg-open: not found

`mmlh`が問題が起こったことに気づいているようでその下に`mmlh show --terminal 1`と同様の内容が表示されます。

xdg-utilsをインストールしてみると以下のエラーに変わります。

```powershell
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start "/tmp/mmlh-ex1.html"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

この状況では課題の内容が表示されないのでかなり分かりづらいと思います。

いろいろ調べてみたが`wslpath -w`でファイルパスを変換して`explorer.exe`とかで普通に開けるようです。`xdg-open-wsl`それとも`wsl-open`をインストールすることも解決方法の一つです。

少なくともREADMEに`--terminal`の存在に触れば良いかもしれない。

**Comment by igrep** [comment]
詳しい調査ありがとうございます。残念ながら根本的な対応はとても難しそうです。本来であれば、`wdg-open`が見つからないというエラーは利用している[open-browserパッケージのこの辺り](https://github.com/rightfold/open-browser/blob/1c862a6dc5943cdfe5860a743b9f545584156436/lib/Web/Browser/Linux.hs#L11)で正しく処理され、自動的にターミナルに出力されるはずですが、それがうまく行ってないようなので。
また、将来的にはCLIでの提供はせず、ウェブサービスとして動かすことも視野に入れているという事情もあるので、当面は提案のとおりREADMEへの修正で対応を済ませます。
