### ISSUE TITLE
hpack 使わない？

### ISSUE THREAD

**Issue by matsubara0507** [haskell-jp/makeMistakesToLearnHaskell#15]
https://github.com/sol/hpack

テクニカルな Cabal ファイルを作ろうとしない限りは適度に重複な部分を書かなくてよくて、こっちの方がいいと思うんだけど。

ましては stack を推奨してるなら尚更。

**Comment by igrep** [comment]
cabalのcommon stanzaがもうstackからでも使えるはずなのをすっかり見落としていたので、リファクタリングするならそっちを推したい気もします。
ただ、stack newもそのうちさせる予定だしな。。。stack newはhpackを使うだろうしな。。。

**Comment by matsubara0507** [comment]
comon stanza 知らなんだ
https://github.com/haskell/cabal/issues/2832

**Comment by igrep** [comment]
すみません、ちょっと考えたんですが、やっぱりどちらにしても確かにstackにしたがっている以上はhpackに従った方が無難ですし、READMEの

> このアプリケーションは、Haskellの初心者でもソースコードを編集できるよう、

という方針を考えると、hpackに慣れた人が手を着ける可能性は十分あるので変えます。

**Comment by matsubara0507** [comment]
おk
じゃぁやっとく b

**Comment by matsubara0507** [comment]
#16 で対応した
