### ISSUE TITLE
「入力の取得」の出力結果例が違う

### ISSUE THREAD

**Issue by pythonissam** [haskell-jp/makeMistakesToLearnHaskell#55]
> input.txtという、次のような内容のファイルがあるとき、

> Lorem ipsum dolor sit amet,
> sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
> consectetur adipiscing elit,
> 下👇のように実行すると、

> shell> stack exec runhaskell 3.hs < input.txt
> 下👇のような文字列を出力します。

> sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
> consectetur adipiscing elit,
> Lorem ipsum dolor sit amet,

とありますが、正しくは

> consectetur adipiscing elit,
> sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
> Lorem ipsum dolor sit amet,

ではないでしょうか?

**Comment by igrep** [comment]
報告ありがとうございます！
https://github.com/haskell-jp/makeMistakesToLearnHaskell/pull/56 で直るはずです。
