### ISSUE TITLE
GHCの出力とは無関係な文字列が「GHCの出力」として扱われてしまっている

### ISSUE THREAD

**Issue by igrep** [haskell-jp/makeMistakesToLearnHaskell#67]
https://github.com/haskell-jp/makeMistakesToLearnHaskell/pull/52 の修正について見つかった問題。
`Nice output!`や`Wrong output!`はGHCの出力ではない。。。
早く気づきたかった。。。 😞

**Comment by waddlaw** [comment]
なおしてみまーす！

**Comment by igrep** [comment]
多分全部直ったはずなのでclose
