### ISSUE TITLE
課題などを出力した際、コンソール画面から先頭がはみ出してしまう

### ISSUE THREAD

**Issue by igrep** [haskell-jp/makeMistakesToLearnHaskell#9]
標準出力がttyな場合に `less` などの pagerを通すのがいいんだろうけど、Mac, Linux, Windowsすべてで動くやり方がないものか。

**Comment by igrep** [comment]
むー、やっぱりunixパッケージに依存してるしWindowsでは動かないな。。。妥協案としてはアリだけど。。。

**Comment by igrep** [comment]
実装としては、恐らく`Env`型に`printMarkdown`みたいな関数を追加して、`withMainEnv`関数で終了後に処理するHTMLに変換してブラウザを立ち上げるか、そのままコンソールに出すと良いのではないかと思います。

いじるのは主に https://github.com/haskell-jp/makeMistakesToLearnHaskell/blob/master/src/Education/MakeMistakesToLearnHaskell.hs

**Comment by waddlaw** [comment]
実装する前に質問です。やりたいこととしては以下の内容で合ってますか？

- `cmark` を使ってマークダウンファイルを HTML に変換 (起動時？`show` コマンドの実行毎？)
- `mmlh show n` で `n.html` をブラウザで開く

**Comment by igrep** [comment]
すみません、遅くなりました。
恐らく実装が簡単なのは

- `show`コマンドを実行する都度変換して、
- 「`mmlh show n` で`n.md`を変換したHTMLを開く」だと思っています。

途中まで実装したのを https://github.com/haskell-jp/makeMistakesToLearnHaskell/compare/issue9?expand=1 に上げました（本当に最初のところだけですが）。
tmpファイルがいいかと思ってtemporaryパッケージを追加してみたものの、リロードしたら消えちゃう、というのも困るので、実際には使わない方がいいかもしれません。どこに書き込むかはお任せします。
書き込み場所について一点だけ気になるのが、TMPディレクトリー以外だと、ホームディレクトリー以下のどこかになるようにした方がいいと思います。
assets以下だと、root権限でインストールされている可能性も0ではないので。。。
